<?php

use Illuminate\Database\Seeder;

class Sickness extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        DB::table('sicknesses')->insert([
          [ 'sick_name' => 'no_dis',
           'sick_description' => 'ไม่มีโรคประจำตัว',
           'created_at' => date('Y-m-d H:i:s'),
         ],
          [ 'sick_name' => 'has_skin_dis',
           'sick_description' => 'โรคผิวหนัง',
           'created_at' => date('Y-m-d H:i:s'),
         ],
         ['sick_name' => 'has_diabetes_dis',
          'sick_description' => 'โรคเบาหวาน',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_hbp',
          'sick_description' => 'โรคความดันโลหิตสูง',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_dysilpidemia',
          'sick_description' => 'โรคไขมันในเส้นเลือด',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_cardio_vascular',
          'sick_description' => 'โรคหัวใจ',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_renal_and_urological',
          'sick_description' => 'โรคไตและทางเดินปัสสาวะ',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_cancer',
          'sick_description' => 'โรคมะเร็ง',
          'created_at' => date('Y-m-d H:i:s'),
        ],
         ['sick_name' => 'has_stroke',
          'sick_description' => 'โรคหลอดเลือดสมองและหัวใจ',
          'created_at' => date('Y-m-d H:i:s'),
        ],
        ['sick_name' => 'has_parkinson_dis',
         'sick_description' => 'โรคพากินสัน',
         'created_at' => date('Y-m-d H:i:s'),
       ],
       ['sick_name' => 'has_dementia',
        'sick_description' => 'โรคสมองเสื่อม',
        'created_at' => date('Y-m-d H:i:s'),
      ],
      ['sick_name' => 'has_orthipedic',
       'sick_description' => 'โรคกระดูกไขข้อ',
       'created_at' => date('Y-m-d H:i:s'),
     ],
     ['sick_name' => 'has_ALS',
      'sick_description' => 'โรคกล้ามเนื้ออ่อนแรง',
      'created_at' => date('Y-m-d H:i:s'),
    ],
    ['sick_name' => 'has_alz',
     'sick_description' => 'โรคอัลไซเมอร์',
     'created_at' => date('Y-m-d H:i:s'),
   ],
   ['sick_name' => 'has_blood_dis',
    'sick_description' => 'โรคเลือด',
    'created_at' => date('Y-m-d H:i:s'),
  ],
  ['sick_name' => 'has_arthritis',
   'sick_description' => 'โรคข้ออักเสบเรื้อรัง',
   'created_at' => date('Y-m-d H:i:s'),
 ],
 ['sick_name' => 'has_COPD',
  'sick_description' => 'โรคหลอดลมอุดกั้นเรื้อรัง',
  'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_gastrointestinal',
 'sick_description' => 'โรคเกี่ยวกับลำไส้',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_HIV/AIDS',
 'sick_description' => 'โรคเอดส์ HIV',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_post_surgery_recovery',
 'sick_description' => 'เป็นผู้ป่วยพักฟื้นหลังผ่าตัด',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_tracheotomy_ventilation',
 'sick_description' => 'เป็นผู้ป่วยเจาะคอหรือใช้เครื่องช่วยหายใจ',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_NG_tube',
 'sick_description' => 'เป็นผู้ป่วยที่ต้องให้อาหารทางสาย',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_paralysis',
 'sick_description' => 'อัมพาต/อัมพฤกษ์',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_vision_eye_dis',
 'sick_description' => 'บกพร่องทางการมองเห็น์',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_hearing_dis',
 'sick_description' => 'บกพร่องทางการได้ยิน',
 'created_at' => date('Y-m-d H:i:s'),
],
['sick_name' => 'has_psychictric',
 'sick_description' => 'บกพร่องทางจิต/มีอาการทางจิต',
 'created_at' => date('Y-m-d H:i:s'),
],
       ]);
    }
}
